# Ultralytics 🚀 AGPL-3.0 License
# YOLOv11 model adapted with a DINOv3-ConvNeXt-Tiny backbone

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants - IGNORED by fixed-size DINOv3 backbone
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]

# DINOv3-ConvNeXt-Tiny backbone with adapter layers
backbone:
  # [from, repeats, module, args]
  - [-1, 1, DINOv3ConvNeXtTinyBackbone, ['dinov3-main', 'dinov3-main/checkpoints/dinov3_convnext_tiny.pth']] # 0

  - [ 0, 1, FeatureSelector, [ 0, 192 ] ] # 4
  - [-1, 1, Conv, [256, 1, 1]] # 5   P3

  - [ 0, 1, FeatureSelector, [ 1, 384 ] ] # 6
  - [-1, 1, Conv, [512, 1, 1]] #7    P4

  - [ 0, 1, FeatureSelector, [ 2, 768 ] ] # 8
  - [-1, 1, Conv, [1024, 1, 1]] # 9  P5

  - [ -1, 1, SPPF, [ 1024, 5 ] ] # 10
  - [ -1, 2, C2PSA, [ 1024 ] ] # 11


# YOLO11n head, re-routed to connect to the new backbone
head:
  # [from, repeats, module, args]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 12 - Upsample P5
  - [[-1, 4], 1, Concat, [1]] # 13 - cat backbone P4 (now from our P4 adapter at layer 4)
  - [-1, 2, C3k2, [512, False]] # 14

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 15 - Upsample
  - [[-1, 2], 1, Concat, [1]] # 16 - cat backbone P3 (now from our P3 adapter at layer 2)
  - [-1, 2, C3k2, [256, False]] # 17 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]] # 18 - Downsample
  - [[-1, 11], 1, Concat, [1]] # 19 - cat head P4 (from layer 9)
  - [-1, 2, C3k2, [512, False]] # 20 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]] # 21 - Downsample
  - [[-1, 8], 1, Concat, [1]] # 22 - cat head P5 (now from our P5 adapter at layer 6)
  - [-1, 2, C3k2, [1024, True]] # 23 (P5/32-large)

  - [[14, 17, 20], 1, Detect, [nc]] # Detect(P3, P4, P5)